# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hw9' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hw9

  pod 'SwiftyJSON', '~> 4.0'
  pod 'Alamofire', '~> 5.1'
  pod 'Toast-Swift', '~> 5.0.0'
  pod "SwiftSpinner"
  pod 'ChartsRealm'
  pod 'XLPagerTabStrip', '~> 9.0'


end
